[build-system]
requires = ["meson-python", "pybind11"]
build-backend = "mesonpy"

[project]
name = "ic_ps"
version = "0.0.1"
requires-python = ">=3.11.9"
dependencies = [
	"numpy >= 1.24.4",
	"scipy >= 1.11.3",
	"pandas >= 2.1.1",
]
readme = "README.md"
